package minipbl;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.*;
import controller.koneksi;
import java.awt.HeadlessException;
import java.awt.Color;

public class Login extends javax.swing.JFrame {

    
    Connection conn = koneksi.getKoneksi();
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    public Login() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PTrans = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JPasswordField();
        btnMhs = new javax.swing.JButton();
        btnLbr = new javax.swing.JButton();
        btnDsn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PTrans.setBackground(new Color (255,255,255,180));
        PTrans.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel4.setText("Password");
        PTrans.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, -1, -1));

        txtuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtuserActionPerformed(evt);
            }
        });
        PTrans.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 170, -1));

        txtpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpassActionPerformed(evt);
            }
        });
        PTrans.add(txtpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 170, -1));

        btnMhs.setBackground(new java.awt.Color(27, 124, 180));
        btnMhs.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnMhs.setForeground(new java.awt.Color(255, 255, 255));
        btnMhs.setText("Mahasiswa");
        btnMhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMhsActionPerformed(evt);
            }
        });
        PTrans.add(btnMhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 100, 30));

        btnLbr.setBackground(new java.awt.Color(27, 124, 180));
        btnLbr.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnLbr.setForeground(new java.awt.Color(255, 255, 255));
        btnLbr.setText("Laboran");
        btnLbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLbrActionPerformed(evt);
            }
        });
        PTrans.add(btnLbr, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 350, 100, 30));

        btnDsn.setBackground(new java.awt.Color(27, 124, 180));
        btnDsn.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnDsn.setForeground(new java.awt.Color(255, 255, 255));
        btnDsn.setText("Dosen");
        btnDsn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDsnActionPerformed(evt);
            }
        });
        PTrans.add(btnDsn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 100, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setText("Username");
        PTrans.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Castellar", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(27, 124, 180));
        jLabel5.setText("PERALATAN LABORATORIUM POLIBATAM");
        PTrans.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Castellar", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 124, 180));
        jLabel6.setText("APLIKASI PEMINJAMAN DAN PENGELOLAAN");
        PTrans.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Castellar", 1, 28)); // NOI18N
        jLabel2.setText("LOGIN");
        PTrans.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        jPanel1.add(PTrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 890, 490));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/wall4.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtuserActionPerformed

    private void txtpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpassActionPerformed

    private void btnMhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMhsActionPerformed
        String sql = "SELECT * FROM mahasiswa WHERE username=? and password=? ";
        try{
            pst= conn.prepareStatement(sql);
            pst.setString(1, txtuser.getText());
            pst.setString(2, String.valueOf(txtpass.getPassword()));
            rs=pst.executeQuery();
            if(rs.next()){
                if(rs.getString("id_mahasiswa").equals("3") && txtuser.getText().equals(rs.getString("username")) && String.valueOf(txtpass.getPassword()).equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Selamat Datang "+rs.getString("nama"));
                    FormPinjam1 ad = new FormPinjam1();
                    ad.setVisible(true);
                    dispose();
                }else if(rs.getString("id_mahasiswa").equals("4") && txtuser.getText().equals(rs.getString("username")) && String.valueOf(txtpass.getPassword()).equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Selamat Datang "+rs.getString("nama"));
                    FormPinjam2 ad = new FormPinjam2();
                    ad.setVisible(true);
                    dispose();
                }
            }else
            JOptionPane.showMessageDialog(null, "Username atau Password Salah");
        }catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnMhsActionPerformed

    private void btnLbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLbrActionPerformed
        String sql = "SELECT * FROM laboran WHERE username=? and password=? ";
        try{
            pst= conn.prepareStatement(sql);
            pst.setString(1, txtuser.getText());
            pst.setString(2, String.valueOf(txtpass.getPassword()));
            rs=pst.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "Selamat Datang");
                L_Pinjam ad = new L_Pinjam();
                ad.setVisible(true);
                dispose();
            }else
            JOptionPane.showMessageDialog(null, "Username atau Password Salah");
        }catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnLbrActionPerformed

    private void btnDsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDsnActionPerformed
        String sql = "SELECT * FROM dosen WHERE username =? and password =?";
        try{
            pst= conn.prepareStatement(sql);
            pst.setString(1, txtuser.getText());
            pst.setString(2, String.valueOf(txtpass.getPassword()));
            rs=pst.executeQuery();
            if(rs.next()){
                if(rs.getString("id_dosen").equals("1") && txtuser.getText().equals(rs.getString("username")) && String.valueOf(txtpass.getPassword()).equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Selamat Datang "+rs.getString("nama_dosen"));
                    D_1 ad = new D_1();
                    ad.setVisible(true);
                    dispose();
                }else if(rs.getString("id_dosen").equals("2") && txtuser.getText().equals(rs.getString("username")) && String.valueOf(txtpass.getPassword()).equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Selamat Datang "+rs.getString("nama_dosen"));
                    D_2 ad = new D_2();
                    ad.setVisible(true);
                    dispose();
                }else if(rs.getString("id_dosen").equals("3") && txtuser.getText().equals(rs.getString("username")) && String.valueOf(txtpass.getPassword()).equals(rs.getString("password"))){
                    JOptionPane.showMessageDialog(null, "Selamat Datang "+rs.getString("nama_dosen"));
                    D_3 ad = new D_3();
                    ad.setVisible(true);
                    dispose();
                }else
                    JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }else
                JOptionPane.showMessageDialog(null, "Username atau Password Salah");
        }catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnDsnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PTrans;
    private javax.swing.JButton btnDsn;
    private javax.swing.JButton btnLbr;
    private javax.swing.JButton btnMhs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtpass;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
